# Generated by Django 3.2.19 on 2023-05-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserCreationForm',
        ),
    ]
