# Generated by Django 3.2.19 on 2023-05-24 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'permissions': (('view', 'Can view the task '), ('can_create', 'Can create a task'))},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='assign_to',
        ),
        migrations.AddField(
            model_name='todolist',
            name='assign_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
